server:
  port: 8080
  forward-headers-strategy: framework


spring:
  config:
    import: "optional:file:../.env[.properties]"
  application:
    name: api-gateway
  
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      
      routes:
        # Auth Service
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/v1/auth/**, /api/v1/oauth2/**, /api/v1/login/**
          filters:
            - StripPrefix=2
            - PreserveHostHeader

        # Post Service
        - id: post-service-api
          uri: lb://post-service
          predicates:
            - Path=/api/v1/posts/**
          filters:
            - StripPrefix=2

        # Comment Service
        - id: comment-service-api
          uri: lb://comment-service
          predicates:
            - Path=/api/v1/comments/**
          filters:
            - StripPrefix=2

        # Category Service
        - id: category-service-api
          uri: lb://category-service
          predicates:
            - Path=/api/v1/categories/**, /api/v1/tags/**
          filters:
            - StripPrefix=2

        # Media Service
        - id: media-service-api
          uri: lb://media-service
          predicates:
            - Path=/api/v1/media/**
          filters:
            - StripPrefix=2

        # Newsletter Service
        - id: newsletter-service-api
          uri: lb://newsletter-service
          predicates:
            - Path=/api/v1/newsletter/**
          filters:
            - StripPrefix=2

        # Notification Service
        - id: notification-service-api
          uri: lb://notification-service
          predicates:
            - Path=/api/v1/notifications/**
          filters:
            - StripPrefix=2

        - id: notification-service-audit-api
          uri: lb://notification-service
          predicates:
            - Path=/api/v1/audit-logs/**
          filters:
            - StripPrefix=2

        # Payment Service
        - id: payment-service-api
          uri: lb://payment-service
          predicates:
            - Path=/api/v1/payments/**
          filters:
            - StripPrefix=2

springdoc:
  swagger-ui:
    path: /swagger-ui/index.html
    urls:
      - name: auth-service
        url: /api/v1/auth/v3/api-docs
      - name: post-service
        url: /api/v1/posts/v3/api-docs
      - name: category-service
        url: /api/v1/categories/v3/api-docs
      - name: comment-service
        url: /api/v1/comments/v3/api-docs
      - name: media-service
        url: /api/v1/media/v3/api-docs
      - name: newsletter-service
        url: /api/v1/newsletter/v3/api-docs
      - name: notification-service
        url: /api/v1/notifications/v3/api-docs
      - name: payment-service
        url: /api/v1/payments/v3/api-docs

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    hostname: ${EUREKA_INSTANCE_HOSTNAME:localhost}
    prefer-ip-address: ${EUREKA_INSTANCE_PREFER_IP_ADDRESS:false}

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION:86400000}

management:
  endpoints:
    web:
      exposure:
        include: "*"

