server:
  port: ${SERVER_PORT_CATEGORY:8084}

springdoc:
  api-docs:
    enabled: true
    path: /categories/v3/api-docs
  swagger-ui:
    disable-swagger-default-url: true
  override-with-generic-response: false

spring:
  config:
    import: "optional:file:../.env[.properties]"
  application:
    name: category-service
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/category_db?createDatabaseIfNotExist=true
    username: ${CATEGORY_DB_USERNAME}
    password: ${CATEGORY_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

  cache:
    type: simple

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    hostname: ${EUREKA_INSTANCE_HOSTNAME:localhost}
    prefer-ip-address: ${EUREKA_INSTANCE_PREFER_IP_ADDRESS:false}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

