package com.inkwell.post.client;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class ClientDtoTest {

    @Test
    void testCategoryClientTagSummary() {
        CategoryClient.TagSummary tagSummary = new CategoryClient.TagSummary();
        tagSummary.setTagId(1L);
        tagSummary.setName("Tag Name");
        tagSummary.setSlug("tag-slug");
        tagSummary.setPostCount(10L);

        assertEquals(1L, tagSummary.getTagId());
        assertEquals("Tag Name", tagSummary.getName());
        assertEquals("tag-slug", tagSummary.getSlug());
        assertEquals(10L, tagSummary.getPostCount());
        
        // Test toString (generated by @Data)
        assertNotNull(tagSummary.toString());
        CategoryClient.TagSummary other = new CategoryClient.TagSummary();
        other.setTagId(1L);
        other.setName("Tag Name");
        other.setSlug("tag-slug");
        other.setPostCount(10L);
        assertEquals(tagSummary, other);
    }
}
